// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swag init and swag fmt.
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "swagger": "2.0",
    "info": {
        "title": "HCMUT Lost & Found API",
        "description": "API for HCMUT Lost and Found Mobile Application",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@hcmut.edu.vn"
        },
        "version": "1.0"
    },
    "host": "{{.Host}}",
    "basePath": "/api",
    "schemes": ["https", "http"],
    "paths": {
        "/": {
            "get": {
                "description": "Check if server is running",
                "produces": ["text/plain"],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "Hello World - Server is running!",
                        "schema": {"type": "string"}
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns server health status",
                "produces": ["application/json"],
                "summary": "Health check with JSON",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {"$ref": "#/definitions/HealthResponse"}
                    }
                }
            }
        },
        "/items": {
            "get": {
                "description": "Get all public items (lost and found)",
                "produces": ["application/json"],
                "tags": ["Items"],
                "summary": "List all public items",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {"$ref": "#/definitions/ItemResponse"}
                        }
                    }
                }
            },
            "post": {
                "security": [{"Bearer": []}],
                "description": "Create a new lost or found item",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["Items"],
                "summary": "Create item",
                "parameters": [{
                    "description": "Item data",
                    "name": "item",
                    "in": "body",
                    "required": true,
                    "schema": {"$ref": "#/definitions/CreateItemRequest"}
                }],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {"$ref": "#/definitions/ItemResponse"}
                    },
                    "400": {"description": "Bad Request"},
                    "401": {"description": "Unauthorized"}
                }
            }
        },
        "/items/me": {
            "get": {
                "security": [{"Bearer": []}],
                "description": "Get all items created by the authenticated user",
                "produces": ["application/json"],
                "tags": ["Items"],
                "summary": "List my items",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {"$ref": "#/definitions/ItemResponse"}
                        }
                    },
                    "401": {"description": "Unauthorized"}
                }
            }
        },
        "/items/{id}/confirm": {
            "post": {
                "security": [{"Bearer": []}],
                "description": "Mark an item as confirmed (found/returned)",
                "produces": ["application/json"],
                "tags": ["Items"],
                "summary": "Confirm item",
                "parameters": [{
                    "type": "string",
                    "description": "Item ID",
                    "name": "id",
                    "in": "path",
                    "required": true
                }],
                "responses": {
                    "200": {"description": "OK"},
                    "400": {"description": "Bad Request"},
                    "401": {"description": "Unauthorized"}
                }
            }
        },
        "/me": {
            "get": {
                "security": [{"Bearer": []}],
                "description": "Get current authenticated user info",
                "produces": ["application/json"],
                "tags": ["User"],
                "summary": "Get current user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {"$ref": "#/definitions/UserResponse"}
                    },
                    "401": {"description": "Unauthorized"}
                }
            }
        },
        "/profile": {
            "get": {
                "security": [{"Bearer": []}],
                "description": "Get user profile with name and avatar",
                "produces": ["application/json"],
                "tags": ["User"],
                "summary": "Get user profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {"$ref": "#/definitions/ProfileResponse"}
                    },
                    "401": {"description": "Unauthorized"}
                }
            }
        },
        "/chats": {
            "get": {
                "security": [{"Bearer": []}],
                "description": "Get all chats for the authenticated user",
                "produces": ["application/json"],
                "tags": ["Chat"],
                "summary": "List chats",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {"$ref": "#/definitions/ChatResponse"}
                        }
                    },
                    "401": {"description": "Unauthorized"}
                }
            },
            "post": {
                "security": [{"Bearer": []}],
                "description": "Create or get existing chat for an item",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["Chat"],
                "summary": "Create or get chat",
                "parameters": [{
                    "description": "Chat data",
                    "name": "chat",
                    "in": "body",
                    "required": true,
                    "schema": {"$ref": "#/definitions/CreateChatRequest"}
                }],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {"$ref": "#/definitions/ChatResponse"}
                    },
                    "401": {"description": "Unauthorized"}
                }
            }
        },
        "/chats/{id}/messages": {
            "get": {
                "security": [{"Bearer": []}],
                "description": "Get all messages for a chat",
                "produces": ["application/json"],
                "tags": ["Chat"],
                "summary": "Get chat messages",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Chat ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Get messages after this ID (for polling)",
                        "name": "after",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {"$ref": "#/definitions/ChatMessageResponse"}
                        }
                    },
                    "401": {"description": "Unauthorized"},
                    "404": {"description": "Not Found"}
                }
            },
            "post": {
                "security": [{"Bearer": []}],
                "description": "Send a message in a chat",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["Chat"],
                "summary": "Send message",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Chat ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Message content",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {"$ref": "#/definitions/SendMessageRequest"}
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {"$ref": "#/definitions/ChatMessageResponse"}
                    },
                    "401": {"description": "Unauthorized"},
                    "404": {"description": "Not Found"}
                }
            }
        }
    },
    "definitions": {
        "HealthResponse": {
            "type": "object",
            "properties": {
                "status": {"type": "string", "example": "ok"},
                "message": {"type": "string", "example": "Hello World"}
            }
        },
        "UserResponse": {
            "type": "object",
            "properties": {
                "id": {"type": "string", "format": "uuid"},
                "fullName": {"type": "string"},
                "avatarUrl": {"type": "string"}
            }
        },
        "ProfileResponse": {
            "type": "object",
            "properties": {
                "fullName": {"type": "string"},
                "avatarUrl": {"type": "string"}
            }
        },
        "CreateItemRequest": {
            "type": "object",
            "required": ["type", "title", "location", "campus"],
            "properties": {
                "type": {"type": "string", "enum": ["lost", "found"], "example": "lost"},
                "title": {"type": "string", "example": "iPhone 14 Pro"},
                "description": {"type": "string", "example": "Black iPhone with cracked screen"},
                "imageUrls": {"type": "array", "items": {"type": "string"}},
                "location": {"type": "string", "example": "Library floor 2"},
                "campus": {"type": "string", "example": "CS1"},
                "lostAt": {"type": "string", "format": "date-time"},
                "tags": {"type": "array", "items": {"type": "string"}}
            }
        },
        "ItemResponse": {
            "type": "object",
            "properties": {
                "id": {"type": "string", "format": "uuid"},
                "userId": {"type": "string", "format": "uuid"},
                "type": {"type": "string", "enum": ["lost", "found"]},
                "title": {"type": "string"},
                "description": {"type": "string"},
                "imageUrls": {"type": "array", "items": {"type": "string"}},
                "location": {"type": "string"},
                "campus": {"type": "string"},
                "lostAt": {"type": "string", "format": "date-time"},
                "tags": {"type": "array", "items": {"type": "string"}},
                "createdAt": {"type": "string", "format": "date-time"},
                "user": {"$ref": "#/definitions/UserResponse"}
            }
        },
        "CreateChatRequest": {
            "type": "object",
            "required": ["itemId"],
            "properties": {
                "itemId": {"type": "string", "format": "uuid"}
            }
        },
        "ChatResponse": {
            "type": "object",
            "properties": {
                "id": {"type": "string", "format": "uuid"},
                "itemId": {"type": "string", "format": "uuid"},
                "itemTitle": {"type": "string"},
                "itemImage": {"type": "string"},
                "otherUser": {"$ref": "#/definitions/UserResponse"},
                "lastMessage": {"$ref": "#/definitions/ChatMessageResponse"},
                "createdAt": {"type": "string", "format": "date-time"},
                "updatedAt": {"type": "string", "format": "date-time"}
            }
        },
        "SendMessageRequest": {
            "type": "object",
            "required": ["content"],
            "properties": {
                "content": {"type": "string", "example": "Hello, is this your item?"}
            }
        },
        "ChatMessageResponse": {
            "type": "object",
            "properties": {
                "id": {"type": "string", "format": "uuid"},
                "chatId": {"type": "string", "format": "uuid"},
                "senderId": {"type": "string", "format": "uuid"},
                "content": {"type": "string"},
                "createdAt": {"type": "string", "format": "date-time"},
                "sender": {"$ref": "#/definitions/UserResponse"}
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header",
            "description": "Enter: Bearer {token}"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{"https", "http"},
	Title:            "HCMUT Lost & Found API",
	Description:      "API for HCMUT Lost and Found Mobile Application",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}

